plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
}

android {
    namespace 'net.hearnsoft.tcm'
    compileSdk 35

    defaultConfig {
        applicationId "net.hearnsoft.tcm"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0"

        def serverPropsFile = rootProject.file('server.properties')
        if (serverPropsFile.exists()) {
            def serverProps = new Properties()
            serverProps.load(new FileInputStream(serverPropsFile))
            buildConfigField "String", "REMOTE_SERVER", "\"${serverProps['REMOTE_SERVER']}\""
        } else {
            throw new GradleException("server.properties file not found")
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        //启用 ViewBinding
        viewBinding = true
        //启用 BuildConfig
        buildConfig = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation project(':thcdb-sdk')
    implementation project(':alist-sdk')
    implementation fileTree(include: ['*.jar','*.aar'], dir: 'libs')

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.androidx.localbroadcastmanager
    // BannerViewPager
    implementation libs.bannerviewpager
    // Glide
    implementation libs.glide
    // Glide Transformations
    implementation libs.glide.transformations
    // OkHttp
    implementation libs.okhttp
    // Gson
    implementation libs.gson
    // uCrop
    // implementation libs.ucrop
    // MPAndroidChart
    implementation libs.mpandroidchart
    // Lombok
    implementation libs.lombok

    implementation libs.vavr

    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.persistentcookiejar

    // AndroidX Navigation
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui
    // AndroidX Media 3
    implementation libs.androidx.media3.common.ktx
    implementation libs.androidx.media3.exoplayer
    implementation libs.androidx.media3.exoplayer.hls
    implementation libs.androidx.media3.exoplayer.rtsp
    implementation libs.androidx.media3.exoplayer.smoothstreaming
    implementation libs.androidx.media3.session
    implementation libs.androidx.media3.ui
    implementation libs.androidx.media3.datasource.okhttp
    implementation libs.androidx.core.ktx
    // LyricViewX
    implementation libs.lyricviewx
    // Pinyin4J
    implementation libs.pinyin4j
    // OpenImage
    implementation libs.openimagefulllib

    testImplementation libs.junit
    // Lombok annotation processor
    annotationProcessor libs.lombok
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}